// Types file
export default{
    GET_ALL_BEST_SALES_REQUEST:'GET_ALL_BEST_SALES_REQUEST',
    GET_ALL_BEST_SALES_SUCCESS:'GET_ALL_BEST_SALES_SUCCESS',
    GET_ALL_BEST_SALES_FAIL:'GET_ALL_BEST_SALES_FAIL',
    SET_LOADING:'SET_LOADING',
}